# Etapa 1: Servir com Nginx
FROM nginx:alpine

# Copiar os arquivos de build da etapa anterior (agora puxados direto do repositório)
COPY dist /usr/share/nginx/html

# Copiar a configuração personalizada do Nginx
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# Expor a porta 80
EXPOSE 80

# O comando padrão do Nginx já serve os arquivos.
CMD ["nginx", "-g", "daemon off;"]
