
server {
  set $forward_scheme http;
  set $server         "valeouro_app";
  set $port           3001;
  listen 80;
  server_name valeouro.drogariabelafarma.com.br;
  location / {
    include conf.d/include/proxy.conf;
  }
}
